### ISSUE TITLE
Add Logging

### ISSUE THREAD

**Issue by nodh** [ehn-dcc-development/hcert-kotlin#15]
Think about adding a logging library, e.g. https://github.com/MicroUtils/kotlin-logging, to provide additional information about errors in debug builds.

**Comment by JesusMcCloud** [comment]
Logging Infrastructure is set up including basic default logger in [JesusMcCloud/hcert-kotlin: feature/logging](https://github.com/JesusMcCloud/hcert-kotlin/tree/feature/logging)

**Comment by JesusMcCloud** [comment]
This is only really critical for debugging JS, since stack traces are not accurate. On the JVM, throwing exceptions and logging their stack traces suffices.

As for production: Error codes in the result should provide all relevant information to aid debugging.
