### ISSUE TITLE
Replace java.util.Base64 for Android sdk below 26

### ISSUE THREAD

**Issue by vdestombes** [ehn-dcc-development/hcert-kotlin#21]
For Android sdk below 26 (Android 8.0), there will be an exception since java.util.Base64 is unknown.

This can be modified in https://github.com/ehn-dcc-development/hcert-kotlin/blob/main/src/jvmMain/kotlin/ehn/techiop/hcert/kotlin/chain/Extensions.kt

Instead of java.util.Base64.getEncoder().encodeToString(this) and java.util.Base64.getDecoder().decode(this)
org.bouncycastle.util.encoders.Base64.toBase64String(this) et org.bouncycastle.util.encoders.Base64..ecode(this) can be used

**Comment by jnischler** [comment]
correct this needs to change to allow usage on older android devices.

we changed the file in our fork:
https://github.com/section42/hcert-kotlin/commit/e2d2ae3e0408fbdd94354fd38e91722a910b80a2#diff-66b1c9aff517cfce47a40bb207b738ddc194bdb40c0281d35e0288c0b7f3c1b9

tested on android down to 6.0.1.

will create a PR with our changes
