### ISSUE TITLE
Question: Expiration time

### ISSUE THREAD

**Issue by alexKatona** [ehn-dcc-development/hcert-kotlin#26]
Hello @nodh 

I just wanted to ask if there is a requirement from EU to throw away the data if the signing is expired. I was searching for it but could not find.

```
    /**
     * `exp` claim SHALL hold a timestamp.
     * Verifier MUST reject the payload after expiration.
     * It MUST not exceed the validity period of the DSC.
     */
    var expirationTime: Instant? = null
```

**Comment by nodh** [comment]
That's from the hcert-spec: https://github.com/ehn-dcc-development/hcert-spec/blob/main/hcert_spec.md#335-expiration-time
