### ISSUE TITLE
release 1.0.0 is not usable because of fixed bug - please create 1.0.1 or similar

### ISSUE THREAD

**Issue by a-trzewik** [ehn-dcc-development/hcert-kotlin#27]
Please create new release
The 1.0.0 is not usable because of this bug that seems to be already fixed
https://github.com/ehn-dcc-development/hcert-kotlin/commit/85fc85954f4a16d97cc7cfdd81fc15f2fa760bd2
We use the hcert-kotlin as dependency and can not switch to current release
https://github.com/eu-digital-green-certificates/dgca-issuance-service
1.0.0 should be removed anyway

**Comment by nodh** [comment]
That's a good idea: https://github.com/ehn-dcc-development/hcert-kotlin/releases/tag/1.0.1
