### ISSUE TITLE
Public TrustList ?

### ISSUE THREAD

**Issue by jnischler** [ehn-dcc-development/hcert-kotlin#28]
Hey everyone,

is there a public available trust list ?

Same as: 
https://github.com/eu-digital-green-certificates/dgc-participating-countries/issues/10

We would only find an outdated list provided by the TU Graz ?

What lists are you using for your implementation ?

regards
Julian

**Comment by jnischler** [comment]
maybe this is the wrong repo to create this issue but I am quite confused ;)

and another question what is the difference between this 2 projects:
https://github.com/eu-digital-green-certificates
https://github.com/ehn-dcc-development

regards
Julian

**Comment by nodh** [comment]
I can only point you to our demonstration implementation of the [service](https://github.com/ehn-dcc-development/hcert-service-kotlin) at <https://dgc.a-sit.at/ehn/>. There you can get a trust list content and signature file.

**Comment by jnischler** [comment]
Hi,

thanks for the imput.
We already found this api but the data seams to be outdated, or just for test purpose.
For example the German production public keys are missing.

Using this trust list we are able to validate Austrian QR-codes but cant validate German codes.

Have a look at:
https://github.com/eu-digital-green-certificates/dgc-participating-countries/issues/10
The EU won't open there gateway, it needs to be done on a national level.

This doesn't make a lot of sense as everyone is able to open an read the codes but can't validate the codes … I don't get it ;)

Is Austria going to publish a full trust list with only trusted keys and without test keys ?

thanks and best regards

**Comment by jnischler** [comment]
thank will send you an email asap
regards

**Comment by nodh** [comment]
I thik we can close this issue here.
