### ISSUE TITLE
Track cbor-node Upstream

### ISSUE THREAD

**Issue by JesusMcCloud** [ehn-dcc-development/hcert-kotlin#42]
We are currently using a patched cbor library, due to an [issue](https://github.com/hildjj/node-cbor/issues/146) wrt. date strings.
We should therefore track upstream until [PR 145](https://github.com/hildjj/node-cbor/pull/145) is merged.

**Comment by hildjj** [comment]
As mentioned on the issue, you can use this instead of a patched library:

```js
cbor.decodeFirstSync(input, {
  tags: {
    0: x => x
  }
})
```

**Comment by JesusMcCloud** [comment]
Works perfectly, thanks!
1f95791d4a8781b0ae0ea703078d283eb546494a uses upstream cbor-node again.
