### ISSUE TITLE
JVM library missing public constructors

### ISSUE THREAD

**Issue by stefan2k** [ehn-dcc-development/hcert-kotlin#62]
We use the jvm library in a Java11 project and are missing public constructors for _ehn.techiop.hcert.kotlin.chain.impl.TrustListCertificateRepository_ and _ehn.techiop.hcert.kotlin.trust.TrustListDecoderService_.
Basically we added kotlin-hcert-jvm-1.3.0.jar to pom as well as its dependencies and thats it.
Are we missing out on some required steps?

**Comment by nodh** [comment]
That's highly strange. Did you double check that with 1.3.2? Are you missing other constructors?
Because the Java Decompiler seems to show the public constructor:
![Screenshot_2021-09-27_15-00-22](https://user-images.githubusercontent.com/1558009/134913204-fa12701e-8a74-4b7f-bf0c-14b264772c2e.png)

**Comment by stefan2k** [comment]
Thank you for looking into this. Yes we did double check with the latest version.

There is a public constructor for _TrustListCertificateRepository_ but not the one mentioned in the projects README.
We have to provide a _kotlinx.datetime.Clock_ parameter.

_TrustlistDecodeService_ is the one which has no public constructor at all:
![grafik](https://user-images.githubusercontent.com/383840/135147546-e2d27d2d-9531-49c2-ac01-293416dcdafc.png)

**Comment by nodh** [comment]
I've looked into the examples from the Readme again, fixed some minor issues, and provided `@JvmOverloads` for all necessary constructors. Will be included in the next release, thanks for pointing that out.
