### ISSUE TITLE
Java Maven Integration

### ISSUE THREAD

**Issue by Jopasa** [ehn-dcc-development/hcert-kotlin#70]
Dear authors & contributors,

I experience problems when including hcert-kotlin into a java spring boot project using maven. As discussed in the readme, I added the dependency to the built maven artifact using:

```
<dependency>
	<groupId>com.github.ehn-dcc-development</groupId>
	<artifactId>hcert-kotlin</artifactId>
	<version>1.3.2</version>
</dependency>

....
<repository>
	<id>jitpack.io</id>
	<url>https://jitpack.io</url>
</repository>
```

Unfortunately, when trying to test the decode example, compiling fails with:
(this is also same for other jvm-examples from the readme page)

```
The method buildVerificationChain(CertificateRepository, Clock) in the type DefaultChain is not applicable for the arguments (CertificateRepository)
```

Next, I tried to build the hcert-kotlin.jar (v 1.4.0-SNAPSHOT) locally using gradle and import and use it in my local maven repository. Unfortunately, I could only generate the hcert-kotlin-jvm.jar (maybe wrong gradle use, please advise). Using this import the compile error is resolved, but a java runtime error about missing kotlin libraries is thrown.

For further reference during my troubleshooting I found issue https://youtrack.jetbrains.com/issue/KT-35716, which could explain the missing correct static java method.

**Comment by Jopasa** [comment]
@nodh Thank you for your fast response.

regarding gradle after some troubleshooting I could successfully execute the build using the provided command

After some troubleshooting and debugging, I found that the setup works in a simple maven environment, but open switching to spring boot fails. But it only fails when using spring boot maven parent.

That means when using 

```
<parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.3.8.RELEASE</version>
    </parent>
```

and calling the sample code in a simple RestController it fails with 
```
Exception in thread "main" java.lang.NoSuchMethodError: 'long kotlin.time.Duration$Companion.hours-UwyO8pc(int)'
	at ehn.techiop.hcert.kotlin.chain.impl.DefaultCwtService.<init>(DefaultCwtService.kt:21)
	at ehn.techiop.hcert.kotlin.chain.DefaultChain.buildVerificationChain(DefaultChain.kt:34)
	at ehn.techiop.hcert.kotlin.chain.DefaultChain.buildVerificationChain$default(DefaultChain.kt:30)
	at ehn.techiop.hcert.kotlin.chain.DefaultChain.buildVerificationChain(DefaultChain.kt)
	at at.example.Client.main(Client.java:29)
```
But when not using spring boot maven parent (iE all versions of needed components explicitly), there is no error. Additionally, I tested both java 11 and 8 compatibility and both java versions work / don't work equally.

This means this is probably due to some spring boot maven magic, but not related to this project.

**Comment by nodh** [comment]
Maybe upgrading to the latest Spring Boot version 2.5.3 helps?

**Comment by Jopasa** [comment]
> The examples in the Readme have been updated to reflect the current state of the library, as seen in commit [4d9062b](https://github.com/ehn-dcc-development/hcert-kotlin/commit/4d9062bff2c3e7d472f4b71ede828de0d87d6799). So for using release 1.3.2, please have a look at https://github.com/ehn-dcc-development/hcert-kotlin/tree/1.3.2
> 
> To use it locally, run `./gradlew clean publishToMavenLocal`, this will create the artifact `ehn.techiop.hcert:hcert-kotlin-jvm:1.4.0-SNAPSHOT` (among others). Usage of that artifact in an Java/Gradle project with `implementation 'ehn.techiop.hcert:hcert-kotlin-jvm:1.4.0-SNAPSHOT'` and the verification example from the Readme works for me. What error are you getting exactly?

both versions of the README.md (1.3.2 and the mentioned commit) include the same call
```
Chain chain = DefaultChain.buildVerificationChain(repository);
```
