### ISSUE TITLE
Offline Validation for more than 48h 7 VerificationException: Expiration<clock.now()

### ISSUE THREAD

**Issue by dokaha** [ehn-dcc-development/hcert-kotlin#71]
hello, 

i need to do verification of greenpass in offline environment. devices will be offline for longer period of time (maybe months). my problem is, that i'll get
`ehn.techiop.hcert.kotlin.chain.VerificationException: Expiration<clock.now() `
when the trustlist wasn't updated for 2 (?) days.

I'm using the trustlist from a-sit.at

Is there a way to make the verification process accept older data?

thanks!
![exception](https://user-images.githubusercontent.com/91935653/137402532-f8122cd4-dd2b-412f-a6f2-8e9507ff21ce.png)

**Comment by nodh** [comment]
Nearly all services have a constructor parameter, where you can either set an instance of a `Clock`, e.g. to a fixed point in time, or specify the validity that is acceptable.
You are aware that the trust list from dgc.a-sit.at does not contain trust anchors for productive HCERT data, right?
