### ISSUE TITLE
CWT_Expired Error on Check with a new 3/3 valid cert

### ISSUE THREAD

**Issue by visualroam** [ehn-dcc-development/hcert-kotlin#72]
Hello,

we got a issue with new 3/3 certs (not all but mine) doesnt work, it writes CWT_Expired as an error and returns valid false
Its a new GreenPass (9.11).

![Error](https://xd0m3.eu/uploads/studio64_jWFlEcmPYZ.png)

On request i can provide the qrcode.

```
Android 10
implementation 'com.github.ehn-dcc-development.hcert-kotlin:hcert-kotlin-jvm:1.3.0'
```

Best regards,
Dominik

**Comment by visualroam** [comment]
Found it that, there is a 1.3.2 version of hcert-kotlin and this problem vanishs with the upgrade.
Not mention in the fixes but at least it works again. 

1.3.0 --> 1.3.2 update works

**Comment by dokaha** [comment]
hello, i got the same problem but do not know how to update to latest version of this library. 

i got this in my projects build.gradle:
`implementation 'ehn.techiop.hcert:hcert-kotlin-jvm:1.3.0-SNAPSHOT'`

when i change the version number to 1.3.2 the reference cannot get resolved.

please help me with some hints! thank you!
